# This is made with the help from Patrik Svensson's article: https://patriksvensson.se/posts/2020/03/creating-release-artifacts-with-github-actions
# And 2023's BDSA-Group10's adaptation of Patrik Svensson's article: https://github.com/ITU-BDSA23-GROUP10/Chirp

name: .NET

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test

    - name: Publish - Linux
      run: |
        linux_build_name="Chirp-$GITHUB_REF_NAME-linux-x64"

        dotnet publish CLI/CLI.csproj -c Release -o "${linux_build_name}" -r linux-x64 --self-contained false
        7z a "${linux_build_name}.zip" "./${linux_build_name}/*"

        rm -r "$linux_build_name" # Delete output directory

    - name: Publish - macOS
      run: |
        macos_build_name="Chirp-$GITHUB_REF_NAME-macos-x64"

        dotnet publish CLI/CLI.csproj -c Release -o "${macos_build_name}" -r osx-x64 --self-contained false
        7z a "${macos_build_name}.zip" "./${macos_build_name}/*"

        rm -r "$macos_build_name" # Delete output directory

    - name: Publish - Windows
      run: |
        windows_build_name="Chirp-$GITHUB_REF_NAME-windows-x64"

        dotnet publish CLI/CLI.csproj -c Release -o "${windows_build_name}" -r win-x64 --self-contained false
        7z a "${windows_build_name}.zip" "./${windows_build_name}/*"

        rm -r "$windows_build_name" # Delete output directory

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        files: "*.zip"
        draft: false
        prerelease: false

    - name: Finalizing
      run: echo "Application was successfully released!"
