# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOTNET_VERSION: '8.0.x'

  AZURE_BUILD_NAME: "${{ github.event.repository.name }}-${{ github.ref_name }}-azure"

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish Web -c Release -o $AZURE_BUILD_NAME
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AZURE_BUILD_NAME }}
          path: ./${{ env.AZURE_BUILD_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_BUILD_NAME }}
          path: ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D73BD66B792545BD970D5E7EEE32B365 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EE4F038147424164AD814491A6508532 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_56734052A3B84F1BBE07B4B1B8EBC83F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cheeper'
          slot-name: 'Production'
          package: ./app
