# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOTNET_VERSION: '8.0.x'

  AZURE_BUILD_NAME: "${{ github.event.repository.name }}-${{ github.ref_name }}-azure"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish -c Release -o $AZURE_BUILD_NAME
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AZURE_BUILD_NAME }}
          path: ./${{ env.AZURE_BUILD_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_BUILD_NAME }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_474AAEDAAD3C4457BD77ABB320987A79 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A5BE1BD79DC340F7B65A9074B2B852E3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_958F0D33CB6346B7BB56D5C703063845 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup17chirpremotedb'
          slot-name: 'Production'
          package: ./${{ env.AZURE_BUILD_NAME }}
