# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and test

on:
  push:
    branches-ignore:
      - main

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Finalizing
        run: echo "Builded successfully!"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["Chirp.Infrastructure.Tests", "Chirp.Web.Playwright", "Chirp.Web.Tests"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build
      - name: Run test server
        run: dotnet run --project src/Chirp.Web &
      - name: Install playwright
        run: pwsh test/Chirp.Web.Playwright/bin/Debug/net8.0/playwright.ps1 install chromium
      - name: Change directory
        run: cd test/${{ matrix.project }}
      - name: Test
        run: dotnet test
      - name: Finalizing
        run: echo "Tests passed!"

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Lint
        uses: zyactions/dotnet-lint@v1
        with:
          workspace: .
