name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOTNET_VERSION: '8.0.x'

  LINUX_BUILD_NAME: "${{ github.event.repository.name }}-${{ github.ref_name }}-linux-x64"
  MACOS_BUILD_NAME: "${{ github.event.repository.name }}-${{ github.ref_name }}-macos-x64"
  WINDOWS_BUILD_NAME: "${{ github.event.repository.name }}-${{ github.ref_name }}-windows-x64"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet publish src/Chirp.Web -c Release -o "$LINUX_BUILD_NAME" -r linux-x64 --self-contained false
    - name: Compress
      run: 7z -tzip a "$LINUX_BUILD_NAME.zip" "./$LINUX_BUILD_NAME/*"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.LINUX_BUILD_NAME }}.zip
        path: ./${{ env.LINUX_BUILD_NAME }}.zip

  build-macos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet publish src/Chirp.Web -c Release -o "$MACOS_BUILD_NAME" -r osx-x64 --self-contained false
    - name: Compress
      run: 7z -tzip a "$MACOS_BUILD_NAME.zip" "./$MACOS_BUILD_NAME/*"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.MACOS_BUILD_NAME }}.zip
        path: ./${{ env.MACOS_BUILD_NAME }}.zip

  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet publish src/Chirp.Web -c Release -o "$WINDOWS_BUILD_NAME" -r win-x64 --self-contained false
    - name: Compress
      run: 7z -tzip a "$WINDOWS_BUILD_NAME.zip" "./$WINDOWS_BUILD_NAME/*"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.WINDOWS_BUILD_NAME }}.zip
        path: ./${{ env.WINDOWS_BUILD_NAME }}.zip

  release:
    runs-on: ubuntu-latest

    needs: [build-linux, build-macos, build-windows]

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Move zip files to root
      run: find . -name "*.zip" -exec mv {} ./ \;

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: "*.zip"
        draft: false
        prerelease: false
      env:
        GHUB_CLIENT_ID: ${{ secrets.GHUB_CLIENT_ID }}
        GHUB_CLIENT_SECRET: ${{ secrets.GHUB_CLIENT_SECRET }}
