name: Release Report

on:
  push:
    tags:
      - 'report-v[0-9]+.[0-9]+.[0-9]+'

env:
  GROUP_NUMBER: '17'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SVG diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: '-v -tpng ./docs/diagrams/'

      - name: Upload diagrams
        uses: actions/upload-artifact@v4
        with:
          name: diagram
          path: ./docs/diagrams/*.png

      - name: Generate PDF
        uses: docker://pandoc/latex:3.6
        with:
          args: "./docs/report.md -o ./docs/2024_itubdsa_group_${{ env.GROUP_NUMBER }}_report.pdf"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: "./docs/2024_itubdsa_group_${{ env.GROUP_NUMBER }}_report.pdf"
          draft: false
          prerelease: false
        env:
          GHUB_CLIENT_ID: ${{ secrets.GHUB_CLIENT_ID }}
          GHUB_CLIENT_SECRET: ${{ secrets.GHUB_CLIENT_SECRET }}
