name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_NAME: "${{ github.event.repository.name }}-${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        target: [linux-x64, osx-x64, win-x64]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet publish src/Chirp.Web -c Release -o "${{ env.BUILD_NAME }}-${{ matrix.target }}" -r ${{ matrix.target }} --self-contained false
    - name: Compress
      run: 7z -tzip a "${{ env.BUILD_NAME }}-${{ matrix.target }}.zip" "./${{ env.BUILD_NAME }}-${{ matrix.target }}/*"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUILD_NAME }}-${{ matrix.target }}.zip
        path: ./${{ env.BUILD_NAME }}-${{ matrix.target }}.zip

  release:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Move zip files to root
      run: find . -name "*.zip" -exec mv {} ./ \;

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: "*.zip"
        draft: false
        prerelease: false
      env:
        GHUB_CLIENT_ID: ${{ secrets.GHUB_CLIENT_ID }}
        GHUB_CLIENT_SECRET: ${{ secrets.GHUB_CLIENT_SECRET }}
